suite 'Validate Input Chars:', ->

  test 'Invalid chars XML 1.0', ->
    err () -> xml('test').node('node with invalid char \u{0000} in node name')
    err () -> xml('test').node('node with invalid char \u{0001} in node name')
    err () -> xml('test').node('node with invalid char \u{0002} in node name')
    err () -> xml('test').node('node with invalid char \u{0003} in node name')
    err () -> xml('test').node('node with invalid char \u{0004} in node name')
    err () -> xml('test').node('node with invalid char \u{0005} in node name')
    err () -> xml('test').node('node with invalid char \u{0006} in node name')
    err () -> xml('test').node('node with invalid char \u{0007} in node name')
    err () -> xml('test').node('node with invalid char \u{0008} in node name')
    err () -> xml('test').node('node with invalid char \u{000B} in node name')
    err () -> xml('test').node('node with invalid char \u{000C} in node name')
    err () -> xml('test').node('node with invalid char \u{000E} in node name')
    err () -> xml('test').node('node with invalid char \u{000F} in node name')
    err () -> xml('test').node('node with invalid char \u{0010} in node name')
    err () -> xml('test').node('node with invalid char \u{0011} in node name')
    err () -> xml('test').node('node with invalid char \u{0012} in node name')
    err () -> xml('test').node('node with invalid char \u{0013} in node name')
    err () -> xml('test').node('node with invalid char \u{0014} in node name')
    err () -> xml('test').node('node with invalid char \u{0015} in node name')
    err () -> xml('test').node('node with invalid char \u{0016} in node name')
    err () -> xml('test').node('node with invalid char \u{0017} in node name')
    err () -> xml('test').node('node with invalid char \u{0018} in node name')
    err () -> xml('test').node('node with invalid char \u{001A} in node name')
    err () -> xml('test').node('node with invalid char \u{001B} in node name')
    err () -> xml('test').node('node with invalid char \u{001C} in node name')
    err () -> xml('test').node('node with invalid char \u{001D} in node name')
    err () -> xml('test').node('node with invalid char \u{001E} in node name')
    err () -> xml('test').node('node with invalid char \u{001F} in node name')
    err () -> xml('test').node('node with invalid char \u{D800} in node name')
    err () -> xml('test').node('node with invalid char \u{DFFF} in node name')
    err () -> xml('test').node('node with invalid char \u{FFFE} in node name')
    err () -> xml('test').node('node with invalid char \u{FFFF} in node name')
    
  test 'Invalid chars XML 1.1', ->
    err () -> xml('test', { version: '1.1' }).node('node with invalid char \u{0000} in node name')
    err () -> xml('test', { version: '1.1' }).node('node with invalid char \u{D800} in node name')
    err () -> xml('test', { version: '1.1' }).node('node with invalid char \u{DFFF} in node name')
    err () -> xml('test', { version: '1.1' }).node('node with invalid char \u{FFFE} in node name')
    err () -> xml('test', { version: '1.1' }).node('node with invalid char \u{FFFF} in node name')
    eq(
      xml('char_\u{0008}_valid_in_XML_1.1', { headless: true, version: '1.1' }).end()
      '<char_\u{0008}_valid_in_XML_1.1/>'
    )
